CREATE TABLE Sellers (
    SellerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Cheie primara cu auto-increment
    Name VARCHAR2(100) NOT NULL UNIQUE,                             -- Numele vanzatorului (unic)
    Email VARCHAR2(100) NOT NULL UNIQUE,                            -- Email unic si obligatoriu
    Phone VARCHAR2(15) NOT NULL UNIQUE,                             -- Telefon unic si obligatoriu
    Address VARCHAR2(200) NOT NULL                                  -- Adresa vanzatorului
);

CREATE TABLE Products (
    ProductID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Cheie primara cu auto-increment
    Name VARCHAR2(100) NOT NULL,                                    -- Numele produsului
    Price NUMBER(10, 2) NOT NULL CHECK (Price > 0),                  -- Pret pozitiv
    Stock NUMBER NOT NULL CHECK (Stock >= 0),                        -- Stocul nu poate fi negativ
    Category VARCHAR2(50) NOT NULL,                                  -- Categoria produsului
    SellerID NUMBER,                                                 -- Camp pentru a lega produsul de un vanzator
    CONSTRAINT fk_seller FOREIGN KEY (SellerID) REFERENCES Sellers(SellerID)  -- Legatura cu vanzatorul
);

CREATE TABLE Customers (
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- Cheie primara cu auto-increment
    Name VARCHAR2(100) NOT NULL,                               -- Numele clientului 
    Email VARCHAR2(100) NOT NULL UNIQUE,                              -- Email unic si obligatoriu
    Phone VARCHAR2(15) NOT NULL UNIQUE                                -- Telefon unic si obligatoriu
);

CREATE TABLE Orders (
    OrderID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,     -- Cheie primara cu auto-increment
    CustomerID NUMBER NOT NULL,                                      -- Cheie straina catre Customers
    OrderDate DATE DEFAULT SYSDATE NOT NULL,                          -- Data comenzii (implicit, data curenta)
    Total NUMBER(10, 2) NOT NULL CHECK (Total >= 0),                  -- Totalul comenzii, pozitiv
    CONSTRAINT fk_customer FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID) -- Legatura cu clientii
);

CREATE TABLE OrderDetails (
    OrderID NUMBER PRIMARY KEY,                                      -- Cheie primara unica (fiecare comanda are un singur detaliu)
    ProductID NUMBER NOT NULL,                                        -- Cheie straina catre Products (fiecare detaliu se leaga de un singur produs)
    Quantity NUMBER NOT NULL CHECK (Quantity > 0),                    -- Cantitatea trebuie sa fie pozitiva
    Subtotal NUMBER(10, 2) NOT NULL CHECK (Subtotal >= 0),            -- Subtotal pozitiv
    Delivered CHAR(1) DEFAULT 'N' CHECK (Delivered IN ('Y', 'N')),    -- Stare livrare ('Y' = livrat, 'N' = nelivrat)
    OrderDate DATE DEFAULT SYSDATE NOT NULL,                          -- Data adaugarii produsului la comanda
    CONSTRAINT fk_order FOREIGN KEY (OrderID) REFERENCES Orders(OrderID), -- Legatura cu comanda
    CONSTRAINT fk_product FOREIGN KEY (ProductID) REFERENCES Products(ProductID) -- Legatura cu produsul
);
