DROP TABLE OrderDetails CASCADE CONSTRAINTS;

DROP TABLE Orders CASCADE CONSTRAINTS;


DROP TABLE Customers CASCADE CONSTRAINTS;


DROP TABLE Products CASCADE CONSTRAINTS;


DROP TABLE Sellers CASCADE CONSTRAINTS;
